  # docker-compose.yml
  services:
    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"   # puerto AMQP (para tu app)
        - "15672:15672" # panel web de administración